[colors.primary]
background = "#090d16"
foreground = "#ea4833"

[colors.cursor]
text = "#090d16"
cursor = "#70cfe0"

[colors.selection]
text = "#090d16"
background = "#ea4833"

[colors.normal]
black = "#090d16"
red = "#ef4444"
green = "#10b981"
yellow = "#f59e0b"
blue = "#ea4833"
magenta = "#70cfe0"
cyan = "#06b6d4"
white = "#ea4833"

[colors.bright]
black = "#334155"
red = "#f87171"
green = "#34d399"
yellow = "#fbbf24"
blue = "#ea4833"
magenta = "#70cfe0"
cyan = "#67e8f9"
white = "#ffffff"
