[colors.primary]
background = "#090d16"
foreground = "#4f94ea"

[colors.cursor]
text = "#090d16"
cursor = "#c3e062"

[colors.selection]
text = "#090d16"
background = "#4f94ea"

[colors.normal]
black = "#090d16"
red = "#ef4444"
green = "#10b981"
yellow = "#f59e0b"
blue = "#4f94ea"
magenta = "#c3e062"
cyan = "#06b6d4"
white = "#4f94ea"

[colors.bright]
black = "#334155"
red = "#f87171"
green = "#34d399"
yellow = "#fbbf24"
blue = "#4f94ea"
magenta = "#c3e062"
cyan = "#67e8f9"
white = "#ffffff"
