accent = "#ea4833"
cursor = "#70cfe0"
foreground = "#f8fafc"
background = "#090d16"
selection_foreground = "#090d16"
selection_background = "#ea4833"

# Dynamic Window Borders
hyprland_active_border = "#ea4833 #70cfe0 45deg"
hyprland_inactive_border = "rgba(15,23,42,0.65)"

color0 = "#0f172a"
color1 = "#ef4444"
color2 = "#10b981"
color3 = "#f59e0b"
color4 = "#ea4833"
color5 = "#70cfe0"
color6 = "#06b6d4"
color7 = "#e2e8f0"
color8 = "#334155"
color9 = "#f87171"
color10 = "#34d399"
color11 = "#fbbf24"
color12 = "#ea4833"
color13 = "#70cfe0"
color14 = "#67e8f9"
color15 = "#ffffff"
