accent = "#67b3ea"
cursor = "#70e0a7"
foreground = "#f8fafc"
background = "#090d16"
selection_foreground = "#090d16"
selection_background = "#67b3ea"

# Dynamic Window Borders
hyprland_active_border = "#67b3ea #70e0a7 45deg"
hyprland_inactive_border = "rgba(15,23,42,0.65)"

color0 = "#0f172a"
color1 = "#ef4444"
color2 = "#10b981"
color3 = "#f59e0b"
color4 = "#67b3ea"
color5 = "#70e0a7"
color6 = "#06b6d4"
color7 = "#e2e8f0"
color8 = "#334155"
color9 = "#f87171"
color10 = "#34d399"
color11 = "#fbbf24"
color12 = "#67b3ea"
color13 = "#70e0a7"
color14 = "#67e8f9"
color15 = "#ffffff"
