accent = "#ff3388"
cursor = "#ffd600"
foreground = "#f8fafc"
background = "#080b12"
selection_foreground = "#ffffff"
selection_background = "#004b87"

color0 = "#0f172a"
color1 = "#ff2a55"
color2 = "#00e676"
color3 = "#ffb300"
color4 = "#00b0ff"
color5 = "#d500f9"
color6 = "#00f0ff"
color7 = "#e2e8f0"
color8 = "#334155"
color9 = "#ff5478"
color10 = "#69f0ae"
color11 = "#ffe082"
color12 = "#80d8ff"
color13 = "#e040fb"
color14 = "#a5f3fc"
color15 = "#ffffff"
