# Shinsekai (新世界) Dynamic Lock Screen
$color           = rgb(090D16)
$inner_color     = rgba(9, 13, 22, 0.88)
$outer_color     = rgb(2CF535)
$accent_color    = rgb(B528E0)
$font_color      = rgb(F8FAFC)
$placeholder_color = rgba(248, 250, 252, 0.50)
$check_color     = rgb(B528E0)

background {
    blur_passes = 3
    blur_size   = 8
    vibrancy    = 0.90
    vibrancy_darkness = 0.25
}
