# Shinsekai (新世界) Lock Screen
$color           = rgb(090D16)
$inner_color     = rgba(9, 13, 22, 0.88)
$outer_color     = rgb(67B3EA)
$accent_color    = rgb(70E0A7)
$font_color      = rgb(F8FAFC)
$placeholder_color = rgba(248, 250, 252, 0.50)
$check_color     = rgb(70E0A7)

background {
    blur_passes = 3
    blur_size   = 8
    vibrancy    = 0.9
    vibrancy_darkness = 0.25
}
