background       = "rgba(9, 13, 22, 0.70)"
background-alpha = 0.90
text             = "#f8fafc"
placeholder      = "#eed132"
text-error       = "#ef4444"
border           = "rgba(238, 209, 50, 0.50)"
border-active    = "#eed132"
border-error     = "#ef4444"
