# Shinsekai Anime Starship Prompt
add_newline = true
command_timeout = 200
format = "[$directory]($style) [❯](bold #38bdf8)[❯](bold #00e5ff) "

[character]
error_symbol = "[✗](bold #ef4444)"
success_symbol = "[❯](bold #38bdf8)"

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold #38bdf8"
read_only = " 󰌾"
read_only_style = "#ef4444"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "italic #38bdf8"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "#00e5ff"
